### ISSUE TITLE
Question, can you ssGlobal, ssCompany, ssUser, ssUserCompany?

### ISSUE THREAD

**Issue by edwinyzh** [monde-sistemas/param-manager#4]
Hi,

This is an excellent piece of code, thanks for sharing. 

Can you add document for `TParamSystemScope = (ssGlobal, ssCompany, ssUser, ssUserCompany)` ? I really want to know how these options affect the storing and reading of the parameters.

**Comment by fabioxgn** [comment]
@edwinyzh thanks for the interest in the project. I've added the documentation in the README file, please take a look to see if it answer your questions. 

#5 

If something is still not clear, please ask so I can update the documentation.

**Comment by edwinyzh** [comment]
Thanks your help, unfortunately, I read the readme file twice again, but it's still not completely to me. How about let me describe my understanding then you make corrections? 

Global: Do you mean the parameters are readable from all Windows account?

User: Do you mean the parameters are only readable by the Windows account who created those params?

Company: well, I have no idea.
User/Company: no idea...

Thanks for your help.

**Comment by fabioxgn** [comment]
@edwinyzh Thanks for the info. The ParamManager isn't aware of the Windows account, what dictate the User which is "logged in" is the UserID property, so in a code example:

``` Delphi
GetParamManager.RegisterParam('P1', 'Default', ssUser, psRemote);

GetParamManager.UserID := '1'; // sets the current user
GetParamManager['P1'] := 'New Value'; // sets the param value for User '1'
Value := GetParamManager['P1']; // Value is 'New Value', since it was set for User '1'

GetParamManager.UserID := '2'; // now we change the current user
Value := GetParamManager['P1']; // Value is 'Default', since we didn't set it for User '2'
```

For company and user company params the logic is the same, but using the `CompanyID` property value alongside the `UserID` value.

Is this clear now? I'll add this code example in the README if it makes it easier to understand.

**Comment by edwinyzh** [comment]
I think I understand it now. When you change the UserID property, you switch the entire set of the parameters, right? Thanks.

**Comment by fabioxgn** [comment]
@edwinyzh yep, that's it. I've added this info and code example in the README, will merge that, thanks.
